### ISSUE TITLE
Link to CDN outdated

### ISSUE THREAD

**Issue by gnbl** [asciimath/asciimath.github.io#23]
The index page https://github.com/asciimath/asciimath.github.io/blob/e5925ea13b8c8ce859ae56fe4df6ef58409dd155/index.html#L98 still provides an URI to https://cdn.mathjax.org/ which has shut down in 2017: https://www.mathjax.org/cdn-shutting-down/

However, it gracefully serves a loader that redirects to cdnjs.cloudflare (mentioned in previous link)

The page https://www.mathjax.org/#gettingstarted also provides details on this.

**Comment by drlippman** [comment]
Since the replacement CDN has the MathJax version included in the URL, and it's unlikely we'll keep it updated, I think it might be best to include a reference back to MathJax's website for the specific CDN URL.

**Comment by gnbl** [comment]
It's just the CDN and path, the original link also used `latest`:

https://www.mathjax.org/#gettingstarted

> If you want to **always get the most up-to-date version** without modifying your web pages, use the following instead:
> 
> <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/latest.js?config=TeX-MML-AM_CHTML' async></script>
> 
> Although this refers to a specific version, the **latest.js file will load the most current version** regardless of the one you specified.

**Comment by drlippman** [comment]
Doh!  I hadn't realized they added a `latest.js` option.
