### ISSUE TITLE
Add missing symbols

### ISSUE THREAD

**Issue by adius** [asciimath/asciimath.github.io#8]
Check out the asciimath source code and add missing symbols

**Comment by aslakr** [comment]
`|><`, `><|` & `|><|`

from asciimath/asciimathml@cdfc3445003cded745e8b382516faaa3894760e6

**Comment by aslakr** [comment]
`norm` (and `abs`, `floor`& `ceil`?)

from asciimath/asciimathml@4b6fa3b7595c73900793a3f37672e5ba89e2b046
